// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/ds-crm.proto

package ds_crmpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetTaskByIDRequest struct {
	TaskId               int64    `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTaskByIDRequest) Reset()         { *m = GetTaskByIDRequest{} }
func (m *GetTaskByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetTaskByIDRequest) ProtoMessage()    {}
func (*GetTaskByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dbf8717788f2b5c, []int{0}
}

func (m *GetTaskByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTaskByIDRequest.Unmarshal(m, b)
}
func (m *GetTaskByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTaskByIDRequest.Marshal(b, m, deterministic)
}
func (m *GetTaskByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTaskByIDRequest.Merge(m, src)
}
func (m *GetTaskByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetTaskByIDRequest.Size(m)
}
func (m *GetTaskByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTaskByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTaskByIDRequest proto.InternalMessageInfo

func (m *GetTaskByIDRequest) GetTaskId() int64 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

type GetTaskByIDResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTaskByIDResponse) Reset()         { *m = GetTaskByIDResponse{} }
func (m *GetTaskByIDResponse) String() string { return proto.CompactTextString(m) }
func (*GetTaskByIDResponse) ProtoMessage()    {}
func (*GetTaskByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dbf8717788f2b5c, []int{1}
}

func (m *GetTaskByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTaskByIDResponse.Unmarshal(m, b)
}
func (m *GetTaskByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTaskByIDResponse.Marshal(b, m, deterministic)
}
func (m *GetTaskByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTaskByIDResponse.Merge(m, src)
}
func (m *GetTaskByIDResponse) XXX_Size() int {
	return xxx_messageInfo_GetTaskByIDResponse.Size(m)
}
func (m *GetTaskByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTaskByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTaskByIDResponse proto.InternalMessageInfo

type GetTasksOnStatusRequest struct {
	StatusName           string   `protobuf:"bytes,1,opt,name=status_name,json=statusName,proto3" json:"status_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTasksOnStatusRequest) Reset()         { *m = GetTasksOnStatusRequest{} }
func (m *GetTasksOnStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetTasksOnStatusRequest) ProtoMessage()    {}
func (*GetTasksOnStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dbf8717788f2b5c, []int{2}
}

func (m *GetTasksOnStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTasksOnStatusRequest.Unmarshal(m, b)
}
func (m *GetTasksOnStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTasksOnStatusRequest.Marshal(b, m, deterministic)
}
func (m *GetTasksOnStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTasksOnStatusRequest.Merge(m, src)
}
func (m *GetTasksOnStatusRequest) XXX_Size() int {
	return xxx_messageInfo_GetTasksOnStatusRequest.Size(m)
}
func (m *GetTasksOnStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTasksOnStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTasksOnStatusRequest proto.InternalMessageInfo

func (m *GetTasksOnStatusRequest) GetStatusName() string {
	if m != nil {
		return m.StatusName
	}
	return ""
}

type GetTasksOnStatusResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTasksOnStatusResponse) Reset()         { *m = GetTasksOnStatusResponse{} }
func (m *GetTasksOnStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetTasksOnStatusResponse) ProtoMessage()    {}
func (*GetTasksOnStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dbf8717788f2b5c, []int{3}
}

func (m *GetTasksOnStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTasksOnStatusResponse.Unmarshal(m, b)
}
func (m *GetTasksOnStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTasksOnStatusResponse.Marshal(b, m, deterministic)
}
func (m *GetTasksOnStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTasksOnStatusResponse.Merge(m, src)
}
func (m *GetTasksOnStatusResponse) XXX_Size() int {
	return xxx_messageInfo_GetTasksOnStatusResponse.Size(m)
}
func (m *GetTasksOnStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTasksOnStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTasksOnStatusResponse proto.InternalMessageInfo

type GetUserTasksRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserTasksRequest) Reset()         { *m = GetUserTasksRequest{} }
func (m *GetUserTasksRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserTasksRequest) ProtoMessage()    {}
func (*GetUserTasksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dbf8717788f2b5c, []int{4}
}

func (m *GetUserTasksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserTasksRequest.Unmarshal(m, b)
}
func (m *GetUserTasksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserTasksRequest.Marshal(b, m, deterministic)
}
func (m *GetUserTasksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserTasksRequest.Merge(m, src)
}
func (m *GetUserTasksRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserTasksRequest.Size(m)
}
func (m *GetUserTasksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserTasksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserTasksRequest proto.InternalMessageInfo

func (m *GetUserTasksRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetUserTasksResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserTasksResponse) Reset()         { *m = GetUserTasksResponse{} }
func (m *GetUserTasksResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserTasksResponse) ProtoMessage()    {}
func (*GetUserTasksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dbf8717788f2b5c, []int{5}
}

func (m *GetUserTasksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserTasksResponse.Unmarshal(m, b)
}
func (m *GetUserTasksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserTasksResponse.Marshal(b, m, deterministic)
}
func (m *GetUserTasksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserTasksResponse.Merge(m, src)
}
func (m *GetUserTasksResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserTasksResponse.Size(m)
}
func (m *GetUserTasksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserTasksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserTasksResponse proto.InternalMessageInfo

type TaskCreateRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskCreateRequest) Reset()         { *m = TaskCreateRequest{} }
func (m *TaskCreateRequest) String() string { return proto.CompactTextString(m) }
func (*TaskCreateRequest) ProtoMessage()    {}
func (*TaskCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dbf8717788f2b5c, []int{6}
}

func (m *TaskCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskCreateRequest.Unmarshal(m, b)
}
func (m *TaskCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskCreateRequest.Marshal(b, m, deterministic)
}
func (m *TaskCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskCreateRequest.Merge(m, src)
}
func (m *TaskCreateRequest) XXX_Size() int {
	return xxx_messageInfo_TaskCreateRequest.Size(m)
}
func (m *TaskCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TaskCreateRequest proto.InternalMessageInfo

type TaskCreateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskCreateResponse) Reset()         { *m = TaskCreateResponse{} }
func (m *TaskCreateResponse) String() string { return proto.CompactTextString(m) }
func (*TaskCreateResponse) ProtoMessage()    {}
func (*TaskCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dbf8717788f2b5c, []int{7}
}

func (m *TaskCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskCreateResponse.Unmarshal(m, b)
}
func (m *TaskCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskCreateResponse.Marshal(b, m, deterministic)
}
func (m *TaskCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskCreateResponse.Merge(m, src)
}
func (m *TaskCreateResponse) XXX_Size() int {
	return xxx_messageInfo_TaskCreateResponse.Size(m)
}
func (m *TaskCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TaskCreateResponse proto.InternalMessageInfo

type TaskRemoveRequest struct {
	TaskId               int64    `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskRemoveRequest) Reset()         { *m = TaskRemoveRequest{} }
func (m *TaskRemoveRequest) String() string { return proto.CompactTextString(m) }
func (*TaskRemoveRequest) ProtoMessage()    {}
func (*TaskRemoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dbf8717788f2b5c, []int{8}
}

func (m *TaskRemoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskRemoveRequest.Unmarshal(m, b)
}
func (m *TaskRemoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskRemoveRequest.Marshal(b, m, deterministic)
}
func (m *TaskRemoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskRemoveRequest.Merge(m, src)
}
func (m *TaskRemoveRequest) XXX_Size() int {
	return xxx_messageInfo_TaskRemoveRequest.Size(m)
}
func (m *TaskRemoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskRemoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TaskRemoveRequest proto.InternalMessageInfo

func (m *TaskRemoveRequest) GetTaskId() int64 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

type TaskRemoveResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskRemoveResponse) Reset()         { *m = TaskRemoveResponse{} }
func (m *TaskRemoveResponse) String() string { return proto.CompactTextString(m) }
func (*TaskRemoveResponse) ProtoMessage()    {}
func (*TaskRemoveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dbf8717788f2b5c, []int{9}
}

func (m *TaskRemoveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskRemoveResponse.Unmarshal(m, b)
}
func (m *TaskRemoveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskRemoveResponse.Marshal(b, m, deterministic)
}
func (m *TaskRemoveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskRemoveResponse.Merge(m, src)
}
func (m *TaskRemoveResponse) XXX_Size() int {
	return xxx_messageInfo_TaskRemoveResponse.Size(m)
}
func (m *TaskRemoveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskRemoveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TaskRemoveResponse proto.InternalMessageInfo

type ChangeTaskStatusRequest struct {
	TaskId               int64    `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	NewStatus            string   `protobuf:"bytes,2,opt,name=new_status,json=newStatus,proto3" json:"new_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeTaskStatusRequest) Reset()         { *m = ChangeTaskStatusRequest{} }
func (m *ChangeTaskStatusRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeTaskStatusRequest) ProtoMessage()    {}
func (*ChangeTaskStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dbf8717788f2b5c, []int{10}
}

func (m *ChangeTaskStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeTaskStatusRequest.Unmarshal(m, b)
}
func (m *ChangeTaskStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeTaskStatusRequest.Marshal(b, m, deterministic)
}
func (m *ChangeTaskStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeTaskStatusRequest.Merge(m, src)
}
func (m *ChangeTaskStatusRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeTaskStatusRequest.Size(m)
}
func (m *ChangeTaskStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeTaskStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeTaskStatusRequest proto.InternalMessageInfo

func (m *ChangeTaskStatusRequest) GetTaskId() int64 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *ChangeTaskStatusRequest) GetNewStatus() string {
	if m != nil {
		return m.NewStatus
	}
	return ""
}

type ChangeTaskStatusResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeTaskStatusResponse) Reset()         { *m = ChangeTaskStatusResponse{} }
func (m *ChangeTaskStatusResponse) String() string { return proto.CompactTextString(m) }
func (*ChangeTaskStatusResponse) ProtoMessage()    {}
func (*ChangeTaskStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dbf8717788f2b5c, []int{11}
}

func (m *ChangeTaskStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeTaskStatusResponse.Unmarshal(m, b)
}
func (m *ChangeTaskStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeTaskStatusResponse.Marshal(b, m, deterministic)
}
func (m *ChangeTaskStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeTaskStatusResponse.Merge(m, src)
}
func (m *ChangeTaskStatusResponse) XXX_Size() int {
	return xxx_messageInfo_ChangeTaskStatusResponse.Size(m)
}
func (m *ChangeTaskStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeTaskStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeTaskStatusResponse proto.InternalMessageInfo

type DoCommentTaskRequest struct {
	TaskId               int64    `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	CommentText          string   `protobuf:"bytes,2,opt,name=comment_text,json=commentText,proto3" json:"comment_text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DoCommentTaskRequest) Reset()         { *m = DoCommentTaskRequest{} }
func (m *DoCommentTaskRequest) String() string { return proto.CompactTextString(m) }
func (*DoCommentTaskRequest) ProtoMessage()    {}
func (*DoCommentTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dbf8717788f2b5c, []int{12}
}

func (m *DoCommentTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoCommentTaskRequest.Unmarshal(m, b)
}
func (m *DoCommentTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoCommentTaskRequest.Marshal(b, m, deterministic)
}
func (m *DoCommentTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoCommentTaskRequest.Merge(m, src)
}
func (m *DoCommentTaskRequest) XXX_Size() int {
	return xxx_messageInfo_DoCommentTaskRequest.Size(m)
}
func (m *DoCommentTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DoCommentTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DoCommentTaskRequest proto.InternalMessageInfo

func (m *DoCommentTaskRequest) GetTaskId() int64 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *DoCommentTaskRequest) GetCommentText() string {
	if m != nil {
		return m.CommentText
	}
	return ""
}

type DoCommentTaskResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DoCommentTaskResponse) Reset()         { *m = DoCommentTaskResponse{} }
func (m *DoCommentTaskResponse) String() string { return proto.CompactTextString(m) }
func (*DoCommentTaskResponse) ProtoMessage()    {}
func (*DoCommentTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dbf8717788f2b5c, []int{13}
}

func (m *DoCommentTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoCommentTaskResponse.Unmarshal(m, b)
}
func (m *DoCommentTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoCommentTaskResponse.Marshal(b, m, deterministic)
}
func (m *DoCommentTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoCommentTaskResponse.Merge(m, src)
}
func (m *DoCommentTaskResponse) XXX_Size() int {
	return xxx_messageInfo_DoCommentTaskResponse.Size(m)
}
func (m *DoCommentTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DoCommentTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DoCommentTaskResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GetTaskByIDRequest)(nil), "ds_crm.GetTaskByIDRequest")
	proto.RegisterType((*GetTaskByIDResponse)(nil), "ds_crm.GetTaskByIDResponse")
	proto.RegisterType((*GetTasksOnStatusRequest)(nil), "ds_crm.GetTasksOnStatusRequest")
	proto.RegisterType((*GetTasksOnStatusResponse)(nil), "ds_crm.GetTasksOnStatusResponse")
	proto.RegisterType((*GetUserTasksRequest)(nil), "ds_crm.GetUserTasksRequest")
	proto.RegisterType((*GetUserTasksResponse)(nil), "ds_crm.GetUserTasksResponse")
	proto.RegisterType((*TaskCreateRequest)(nil), "ds_crm.TaskCreateRequest")
	proto.RegisterType((*TaskCreateResponse)(nil), "ds_crm.TaskCreateResponse")
	proto.RegisterType((*TaskRemoveRequest)(nil), "ds_crm.TaskRemoveRequest")
	proto.RegisterType((*TaskRemoveResponse)(nil), "ds_crm.TaskRemoveResponse")
	proto.RegisterType((*ChangeTaskStatusRequest)(nil), "ds_crm.ChangeTaskStatusRequest")
	proto.RegisterType((*ChangeTaskStatusResponse)(nil), "ds_crm.ChangeTaskStatusResponse")
	proto.RegisterType((*DoCommentTaskRequest)(nil), "ds_crm.DoCommentTaskRequest")
	proto.RegisterType((*DoCommentTaskResponse)(nil), "ds_crm.DoCommentTaskResponse")
}

func init() {
	proto.RegisterFile("api/ds-crm.proto", fileDescriptor_2dbf8717788f2b5c)
}

var fileDescriptor_2dbf8717788f2b5c = []byte{
	// 545 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x94, 0xdf, 0x6e, 0x12, 0x41,
	0x14, 0xc6, 0x43, 0x8d, 0x68, 0x4f, 0x6b, 0x42, 0x07, 0x28, 0x38, 0xa5, 0x16, 0xe7, 0xc2, 0x98,
	0x46, 0xd8, 0x44, 0xef, 0xb8, 0x2c, 0x24, 0x86, 0x1b, 0x8d, 0xdb, 0x7a, 0xe3, 0xcd, 0x3a, 0xdd,
	0x9d, 0x20, 0xe2, 0xce, 0xe0, 0xce, 0x60, 0xdb, 0x10, 0x6e, 0xf4, 0x11, 0x7c, 0x34, 0x5f, 0xc1,
	0x07, 0x31, 0xf3, 0x07, 0xf7, 0x0f, 0xbb, 0xe9, 0xe5, 0x9e, 0xf3, 0xcd, 0xf7, 0x3b, 0x9c, 0xf9,
	0x06, 0x68, 0xd0, 0xe5, 0xdc, 0x8b, 0xe4, 0x20, 0x4c, 0xe2, 0xe1, 0x32, 0x11, 0x4a, 0xa0, 0x7a,
	0x24, 0x83, 0x30, 0x89, 0x71, 0x6f, 0x26, 0xc4, 0xec, 0x1b, 0xf3, 0xb4, 0x80, 0x72, 0x2e, 0x14,
	0x55, 0x73, 0xc1, 0xa5, 0x55, 0x91, 0x01, 0xa0, 0xb7, 0x4c, 0x5d, 0x51, 0xb9, 0xb8, 0xb8, 0x9b,
	0x4e, 0x7c, 0xf6, 0x7d, 0xc5, 0xa4, 0x42, 0x1d, 0x78, 0xa4, 0xa8, 0x5c, 0x04, 0xf3, 0xa8, 0x5b,
	0xeb, 0xd7, 0x5e, 0x3e, 0xf0, 0xeb, 0xfa, 0x73, 0x1a, 0x91, 0x36, 0x34, 0x73, 0x72, 0xb9, 0x14,
	0x5c, 0x32, 0x32, 0x82, 0x8e, 0x2b, 0xcb, 0xf7, 0xfc, 0x52, 0x51, 0xb5, 0x92, 0x5b, 0xab, 0x33,
	0x38, 0x90, 0xa6, 0x10, 0x70, 0x1a, 0x33, 0x63, 0xb7, 0xef, 0x83, 0x2d, 0xbd, 0xa3, 0x31, 0x23,
	0x18, 0xba, 0xbb, 0x67, 0x9d, 0xef, 0xd0, 0xe0, 0x3e, 0x4a, 0x96, 0x98, 0x7e, 0x66, 0xbc, 0x95,
	0x64, 0x49, 0x66, 0x3c, 0xfd, 0x39, 0x8d, 0xc8, 0x31, 0xb4, 0xf2, 0x7a, 0xe7, 0xd3, 0x84, 0x23,
	0x5d, 0x18, 0x27, 0x8c, 0x2a, 0xe6, 0x5c, 0x48, 0x0b, 0x50, 0xb6, 0xe8, 0xa4, 0xaf, 0xac, 0xd4,
	0x67, 0xb1, 0xf8, 0xc1, 0xee, 0xdd, 0x87, 0xf3, 0xd8, 0xaa, 0x9d, 0xc7, 0x07, 0xe8, 0x8c, 0xbf,
	0x50, 0x3e, 0x63, 0xba, 0x97, 0x5f, 0x47, 0x95, 0x13, 0x3a, 0x05, 0xe0, 0xec, 0x26, 0xb0, 0x8b,
	0xe9, 0xee, 0x99, 0x35, 0xed, 0x73, 0x76, 0x63, 0x8f, 0xeb, 0x2d, 0xed, 0x5a, 0x3a, 0x9c, 0x0f,
	0xad, 0x89, 0x18, 0x8b, 0x38, 0x66, 0x5c, 0xd9, 0x69, 0xee, 0x61, 0x3d, 0x87, 0xc3, 0xd0, 0xca,
	0x03, 0xc5, 0x6e, 0x95, 0xa3, 0x1d, 0xb8, 0xda, 0x15, 0xbb, 0x55, 0xa4, 0x03, 0xed, 0x82, 0xa7,
	0x85, 0xbd, 0xfe, 0x55, 0x87, 0x87, 0x93, 0xcb, 0x71, 0x12, 0xa3, 0x10, 0x0e, 0x32, 0x59, 0x40,
	0x78, 0x68, 0x03, 0x37, 0xdc, 0xcd, 0x13, 0x3e, 0x29, 0xed, 0xb9, 0xf1, 0x4f, 0x7e, 0xfe, 0xf9,
	0xfb, 0x7b, 0xaf, 0x8d, 0x9a, 0x26, 0xa2, 0x7a, 0x44, 0x6f, 0xed, 0xe6, 0xde, 0xa0, 0x0d, 0x34,
	0x8a, 0xe9, 0x40, 0x67, 0x05, 0xb7, 0x62, 0xe6, 0x70, 0xbf, 0x5a, 0xe0, 0x98, 0x2f, 0x0c, 0xb3,
	0x8f, 0x9e, 0xa5, 0x4c, 0xbb, 0x79, 0x6f, 0x9d, 0x49, 0xeb, 0x06, 0x2d, 0xe0, 0x30, 0x1b, 0x28,
	0x94, 0xfd, 0x21, 0xc5, 0x58, 0xe2, 0x5e, 0x79, 0xd3, 0x21, 0xfb, 0x06, 0x89, 0x51, 0x37, 0x45,
	0xea, 0xd4, 0x7a, 0x6b, 0x17, 0xe5, 0x0d, 0xfa, 0x0c, 0x90, 0x06, 0x12, 0x3d, 0xdd, 0xba, 0xed,
	0x24, 0x17, 0xe3, 0xb2, 0x56, 0x7e, 0x9b, 0xa4, 0x91, 0x62, 0x42, 0xa3, 0x18, 0xd5, 0xce, 0xb7,
	0x04, 0x1b, 0xd7, 0x3c, 0x21, 0x17, 0xf8, 0x3c, 0xa1, 0x90, 0xee, 0x12, 0x42, 0x62, 0x14, 0x9a,
	0x70, 0x07, 0x8d, 0x62, 0x4e, 0xd3, 0xfb, 0xaa, 0x78, 0x14, 0xe9, 0x7d, 0x55, 0x46, 0x9c, 0x18,
	0x66, 0x8f, 0x74, 0x8a, 0xf7, 0x35, 0x08, 0xcd, 0x11, 0x8d, 0xfe, 0x0a, 0x4f, 0x72, 0x91, 0x45,
	0xff, 0xef, 0xa3, 0xec, 0x75, 0xe0, 0xd3, 0x8a, 0xae, 0x23, 0xf6, 0x0c, 0xf1, 0x98, 0x1c, 0x65,
	0xf6, 0x68, 0x65, 0xa3, 0xda, 0xf9, 0x05, 0x7c, 0x7a, 0x6c, 0x4f, 0x2f, 0xaf, 0xaf, 0xeb, 0xe6,
	0x9f, 0xf4, 0xcd, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd3, 0x8e, 0xec, 0xa3, 0x83, 0x05, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DSCrmClient is the client API for DSCrm service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DSCrmClient interface {
	GetTaskByID(ctx context.Context, in *GetTaskByIDRequest, opts ...grpc.CallOption) (*GetTaskByIDResponse, error)
	GetTasksOnStatus(ctx context.Context, in *GetTasksOnStatusRequest, opts ...grpc.CallOption) (*GetTasksOnStatusResponse, error)
	GetUserTasks(ctx context.Context, in *GetUserTasksRequest, opts ...grpc.CallOption) (*GetUserTasksResponse, error)
	TaskCreate(ctx context.Context, in *TaskCreateRequest, opts ...grpc.CallOption) (*TaskCreateResponse, error)
	TaskRemove(ctx context.Context, in *TaskRemoveRequest, opts ...grpc.CallOption) (*TaskRemoveResponse, error)
	ChangeTaskStatus(ctx context.Context, in *ChangeTaskStatusRequest, opts ...grpc.CallOption) (*ChangeTaskStatusResponse, error)
	DoCommentTask(ctx context.Context, in *DoCommentTaskRequest, opts ...grpc.CallOption) (*DoCommentTaskResponse, error)
}

type dSCrmClient struct {
	cc grpc.ClientConnInterface
}

func NewDSCrmClient(cc grpc.ClientConnInterface) DSCrmClient {
	return &dSCrmClient{cc}
}

func (c *dSCrmClient) GetTaskByID(ctx context.Context, in *GetTaskByIDRequest, opts ...grpc.CallOption) (*GetTaskByIDResponse, error) {
	out := new(GetTaskByIDResponse)
	err := c.cc.Invoke(ctx, "/ds_crm.DSCrm/GetTaskByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dSCrmClient) GetTasksOnStatus(ctx context.Context, in *GetTasksOnStatusRequest, opts ...grpc.CallOption) (*GetTasksOnStatusResponse, error) {
	out := new(GetTasksOnStatusResponse)
	err := c.cc.Invoke(ctx, "/ds_crm.DSCrm/GetTasksOnStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dSCrmClient) GetUserTasks(ctx context.Context, in *GetUserTasksRequest, opts ...grpc.CallOption) (*GetUserTasksResponse, error) {
	out := new(GetUserTasksResponse)
	err := c.cc.Invoke(ctx, "/ds_crm.DSCrm/GetUserTasks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dSCrmClient) TaskCreate(ctx context.Context, in *TaskCreateRequest, opts ...grpc.CallOption) (*TaskCreateResponse, error) {
	out := new(TaskCreateResponse)
	err := c.cc.Invoke(ctx, "/ds_crm.DSCrm/TaskCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dSCrmClient) TaskRemove(ctx context.Context, in *TaskRemoveRequest, opts ...grpc.CallOption) (*TaskRemoveResponse, error) {
	out := new(TaskRemoveResponse)
	err := c.cc.Invoke(ctx, "/ds_crm.DSCrm/TaskRemove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dSCrmClient) ChangeTaskStatus(ctx context.Context, in *ChangeTaskStatusRequest, opts ...grpc.CallOption) (*ChangeTaskStatusResponse, error) {
	out := new(ChangeTaskStatusResponse)
	err := c.cc.Invoke(ctx, "/ds_crm.DSCrm/ChangeTaskStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dSCrmClient) DoCommentTask(ctx context.Context, in *DoCommentTaskRequest, opts ...grpc.CallOption) (*DoCommentTaskResponse, error) {
	out := new(DoCommentTaskResponse)
	err := c.cc.Invoke(ctx, "/ds_crm.DSCrm/DoCommentTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DSCrmServer is the server API for DSCrm service.
type DSCrmServer interface {
	GetTaskByID(context.Context, *GetTaskByIDRequest) (*GetTaskByIDResponse, error)
	GetTasksOnStatus(context.Context, *GetTasksOnStatusRequest) (*GetTasksOnStatusResponse, error)
	GetUserTasks(context.Context, *GetUserTasksRequest) (*GetUserTasksResponse, error)
	TaskCreate(context.Context, *TaskCreateRequest) (*TaskCreateResponse, error)
	TaskRemove(context.Context, *TaskRemoveRequest) (*TaskRemoveResponse, error)
	ChangeTaskStatus(context.Context, *ChangeTaskStatusRequest) (*ChangeTaskStatusResponse, error)
	DoCommentTask(context.Context, *DoCommentTaskRequest) (*DoCommentTaskResponse, error)
}

// UnimplementedDSCrmServer can be embedded to have forward compatible implementations.
type UnimplementedDSCrmServer struct {
}

func (*UnimplementedDSCrmServer) GetTaskByID(ctx context.Context, req *GetTaskByIDRequest) (*GetTaskByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaskByID not implemented")
}
func (*UnimplementedDSCrmServer) GetTasksOnStatus(ctx context.Context, req *GetTasksOnStatusRequest) (*GetTasksOnStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTasksOnStatus not implemented")
}
func (*UnimplementedDSCrmServer) GetUserTasks(ctx context.Context, req *GetUserTasksRequest) (*GetUserTasksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserTasks not implemented")
}
func (*UnimplementedDSCrmServer) TaskCreate(ctx context.Context, req *TaskCreateRequest) (*TaskCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TaskCreate not implemented")
}
func (*UnimplementedDSCrmServer) TaskRemove(ctx context.Context, req *TaskRemoveRequest) (*TaskRemoveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TaskRemove not implemented")
}
func (*UnimplementedDSCrmServer) ChangeTaskStatus(ctx context.Context, req *ChangeTaskStatusRequest) (*ChangeTaskStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeTaskStatus not implemented")
}
func (*UnimplementedDSCrmServer) DoCommentTask(ctx context.Context, req *DoCommentTaskRequest) (*DoCommentTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoCommentTask not implemented")
}

func RegisterDSCrmServer(s *grpc.Server, srv DSCrmServer) {
	s.RegisterService(&_DSCrm_serviceDesc, srv)
}

func _DSCrm_GetTaskByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DSCrmServer).GetTaskByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ds_crm.DSCrm/GetTaskByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DSCrmServer).GetTaskByID(ctx, req.(*GetTaskByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DSCrm_GetTasksOnStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTasksOnStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DSCrmServer).GetTasksOnStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ds_crm.DSCrm/GetTasksOnStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DSCrmServer).GetTasksOnStatus(ctx, req.(*GetTasksOnStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DSCrm_GetUserTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DSCrmServer).GetUserTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ds_crm.DSCrm/GetUserTasks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DSCrmServer).GetUserTasks(ctx, req.(*GetUserTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DSCrm_TaskCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DSCrmServer).TaskCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ds_crm.DSCrm/TaskCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DSCrmServer).TaskCreate(ctx, req.(*TaskCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DSCrm_TaskRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DSCrmServer).TaskRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ds_crm.DSCrm/TaskRemove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DSCrmServer).TaskRemove(ctx, req.(*TaskRemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DSCrm_ChangeTaskStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeTaskStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DSCrmServer).ChangeTaskStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ds_crm.DSCrm/ChangeTaskStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DSCrmServer).ChangeTaskStatus(ctx, req.(*ChangeTaskStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DSCrm_DoCommentTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoCommentTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DSCrmServer).DoCommentTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ds_crm.DSCrm/DoCommentTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DSCrmServer).DoCommentTask(ctx, req.(*DoCommentTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DSCrm_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ds_crm.DSCrm",
	HandlerType: (*DSCrmServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTaskByID",
			Handler:    _DSCrm_GetTaskByID_Handler,
		},
		{
			MethodName: "GetTasksOnStatus",
			Handler:    _DSCrm_GetTasksOnStatus_Handler,
		},
		{
			MethodName: "GetUserTasks",
			Handler:    _DSCrm_GetUserTasks_Handler,
		},
		{
			MethodName: "TaskCreate",
			Handler:    _DSCrm_TaskCreate_Handler,
		},
		{
			MethodName: "TaskRemove",
			Handler:    _DSCrm_TaskRemove_Handler,
		},
		{
			MethodName: "ChangeTaskStatus",
			Handler:    _DSCrm_ChangeTaskStatus_Handler,
		},
		{
			MethodName: "DoCommentTask",
			Handler:    _DSCrm_DoCommentTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/ds-crm.proto",
}
